### ISSUE TITLE
Confusion at register when initialize reqseckey

### ISSUE THREAD

**Issue by slionelr** [funoverip/epowner#3]
After searching for the error causing the registration request to fail I found the the problem is at file ModeRegsiter.pm at line 124.
When you call the function mode_register_download_keys(), it returns ($reqseckey, $srpubkey) but for some reason you confused the two and you put $srpubkey<-reqseckey and $reqseckey<-srpubkey.
Later this will cause registration error of http 403 and a concatenation error at line 154.

After I Switched the two like this:
...
($reqseckey, $srpubkey) = $this->mode_register_download_keys()
...
everything worked fine. for now...

Thank you.

**Comment by funoverip** [comment]
O.M.G. 
This can explain many things indeed. It is a bug that I've searched for a couple of time, as for some servers, it works despite the bug.

Thank you very much, I'll fix the issue ASAP.

Regards

**Comment by gitoffmelawn** [comment]
Receiving the following error when running tool on Kali 2.  All packages are up to date.

Error in dsa_sign: error:0306E06C:bignum routines:BN_mod_inverse:no inverse at Epowner/DSA.pm line 18.

Anybody see this before? Know how to fix it?

**Comment by funoverip** [comment]
Hi,

I haven't tried Kali 2 yet. I'll check as soon as I can.
For now, it might be faster to use a kali1 VM if you can.

Thanks for reporting.

**Comment by gitoffmelawn** [comment]
Thanks for the quick response.  Unfortunately I did try Kali v1 as well and received the same error. I'm not sure what the core issue it.  Let me know if you need more info.

**Comment by slionelr** [comment]
Is it possible that the DSA library is changed after an update an causes problems?

Lionel Richard Saposnik

**Comment by gitoffmelawn** [comment]
Definitely a possibility.  I'm not sure how I would go about fixing this though.  Any suggestions would be welcome.

**Comment by slionelr** [comment]
I remembered now that when I reported the last bug you fixed. I ran it on Kali 2 and it worked. 

Lionel Richard Saposnik

**Comment by gitoffmelawn** [comment]
?That's strange.

I've tried it on fresh installs of both Kali v1 and v2 now and both fail.  The server that I'm targeting is definitely vulnerable, so there must be something else causing the issue.  Thanks for replying.

**Comment by funoverip** [comment]
Hi,

I have just downloaded a fresh VM copy of Kali2 (from https://www.offensive-security.com/kali-linux-vmware-arm-image-download/), installed ePowner from github, installed the needed dependencies through apt-get, and it works well.

It might be related to your target ?
Could you share more info (--verbose) to see where it fails exactly ?

**Comment by funoverip** [comment]
Hi again,

So the crash occurs in Epowner/DSA.pm , at line 18 (my $sig   = $dsa_priv->do_sign($hash))

Could you edit the file to dump some values ? Ex: $hash and $buf
If for any reasons the variables are empty, the call the do_sign() might fails (?)
